-- Tabla de clientes del departamento de Cobros
create table clientes_cobros (
  id bigint generated by default as identity primary key,
  rmc bigint,
  nombre_cliente text,
  sector_barrio text,
  calle text,
  numero text,
  tipo_cliente text,
  categoria text,
  contrato text,
  cantidad numeric,
  valor numeric,
  balance numeric,
  inmueble text,
  telefonos text,
  actualizado_en timestamptz default now()
);

-- Índices para que las búsquedas sean rápidas
create index idx_clientes_cobros_rmc on clientes_cobros (rmc);
create index idx_clientes_cobros_sector on clientes_cobros (sector_barrio);
create index idx_clientes_cobros_categoria on clientes_cobros (categoria);

-- Seguridad: solo el personal que inicie sesión en la app puede ver y editar
alter table clientes_cobros enable row level security;

create policy "Personal autenticado puede ver clientes"
on clientes_cobros for select
to authenticated
using (true);

create policy "Personal autenticado puede agregar clientes"
on clientes_cobros for insert
to authenticated
with check (true);

create policy "Personal autenticado puede actualizar clientes"
on clientes_cobros for update
to authenticated
using (true);
